export enum ErrorCode {
  'USER_NOT_FOUND' = 'USER_NOT_FOUND',
  'USER_ALREADY_EXIST' = 'USER_ALREADY_EXIST',
  'USER_NOT_AUTHORIZED' = 'USER_NOT_AUTHORIZED',
  'TOKEN_NOT_FOUND' = 'TOKEN_NOT_FOUND',
  'INVALID_TOKEN' = 'INVALID_TOKEN',
  'TOKEN_EXPIRED' = 'TOKEN_EXPIRED',
  'GENERAL_ERROR' = 'GENERAL_ERROR',
}
